// Code generated by MockGen. DO NOT EDIT.
// Source: store-service/internal/repository/review_repository.go
//
// Generated by this command:
//
//	mockgen -source=store-service/internal/repository/review_repository.go -destination=store-service/internal/mocks/mock_review_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/1tsndre/mini-go-project/store-service/internal/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockReviewRepository is a mock of ReviewRepository interface.
type MockReviewRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReviewRepositoryMockRecorder
	isgomock struct{}
}

// MockReviewRepositoryMockRecorder is the mock recorder for MockReviewRepository.
type MockReviewRepositoryMockRecorder struct {
	mock *MockReviewRepository
}

// NewMockReviewRepository creates a new mock instance.
func NewMockReviewRepository(ctrl *gomock.Controller) *MockReviewRepository {
	mock := &MockReviewRepository{ctrl: ctrl}
	mock.recorder = &MockReviewRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewRepository) EXPECT() *MockReviewRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReviewRepository) Create(ctx context.Context, review *model.Review) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, review)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReviewRepositoryMockRecorder) Create(ctx, review any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReviewRepository)(nil).Create), ctx, review)
}

// FindByProductID mocks base method.
func (m *MockReviewRepository) FindByProductID(ctx context.Context, productID uuid.UUID, page, perPage int) ([]model.Review, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProductID", ctx, productID, page, perPage)
	ret0, _ := ret[0].([]model.Review)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByProductID indicates an expected call of FindByProductID.
func (mr *MockReviewRepositoryMockRecorder) FindByProductID(ctx, productID, page, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProductID", reflect.TypeOf((*MockReviewRepository)(nil).FindByProductID), ctx, productID, page, perPage)
}

// HasUserPurchased mocks base method.
func (m *MockReviewRepository) HasUserPurchased(ctx context.Context, userID, productID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasUserPurchased", ctx, userID, productID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasUserPurchased indicates an expected call of HasUserPurchased.
func (mr *MockReviewRepositoryMockRecorder) HasUserPurchased(ctx, userID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasUserPurchased", reflect.TypeOf((*MockReviewRepository)(nil).HasUserPurchased), ctx, userID, productID)
}

// HasUserReviewed mocks base method.
func (m *MockReviewRepository) HasUserReviewed(ctx context.Context, userID, productID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasUserReviewed", ctx, userID, productID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasUserReviewed indicates an expected call of HasUserReviewed.
func (mr *MockReviewRepositoryMockRecorder) HasUserReviewed(ctx, userID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasUserReviewed", reflect.TypeOf((*MockReviewRepository)(nil).HasUserReviewed), ctx, userID, productID)
}
