// Code generated by MockGen. DO NOT EDIT.
// Source: store-service/internal/repository/store_repository.go
//
// Generated by this command:
//
//	mockgen -source=store-service/internal/repository/store_repository.go -destination=store-service/internal/mocks/mock_store_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/1tsndre/mini-go-project/store-service/internal/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStoreRepository is a mock of StoreRepository interface.
type MockStoreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStoreRepositoryMockRecorder
	isgomock struct{}
}

// MockStoreRepositoryMockRecorder is the mock recorder for MockStoreRepository.
type MockStoreRepositoryMockRecorder struct {
	mock *MockStoreRepository
}

// NewMockStoreRepository creates a new mock instance.
func NewMockStoreRepository(ctrl *gomock.Controller) *MockStoreRepository {
	mock := &MockStoreRepository{ctrl: ctrl}
	mock.recorder = &MockStoreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreRepository) EXPECT() *MockStoreRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStoreRepository) Create(ctx context.Context, store *model.Store) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, store)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStoreRepositoryMockRecorder) Create(ctx, store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStoreRepository)(nil).Create), ctx, store)
}

// FindByID mocks base method.
func (m *MockStoreRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockStoreRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockStoreRepository)(nil).FindByID), ctx, id)
}

// FindByUserID mocks base method.
func (m *MockStoreRepository) FindByUserID(ctx context.Context, userID uuid.UUID) (*model.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockStoreRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockStoreRepository)(nil).FindByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockStoreRepository) Update(ctx context.Context, store *model.Store) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, store)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStoreRepositoryMockRecorder) Update(ctx, store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStoreRepository)(nil).Update), ctx, store)
}
