// Code generated by MockGen. DO NOT EDIT.
// Source: store-service/internal/repository/order_repository.go
//
// Generated by this command:
//
//	mockgen -source=store-service/internal/repository/order_repository.go -destination=store-service/internal/mocks/mock_order_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/1tsndre/mini-go-project/store-service/internal/model"
	repository "github.com/1tsndre/mini-go-project/store-service/internal/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// CancelAndRestock mocks base method.
func (m *MockOrderRepository) CancelAndRestock(ctx context.Context, id uuid.UUID, fromStatus string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelAndRestock", ctx, id, fromStatus)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelAndRestock indicates an expected call of CancelAndRestock.
func (mr *MockOrderRepositoryMockRecorder) CancelAndRestock(ctx, id, fromStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAndRestock", reflect.TypeOf((*MockOrderRepository)(nil).CancelAndRestock), ctx, id, fromStatus)
}

// CreateOrdersWithStock mocks base method.
func (m *MockOrderRepository) CreateOrdersWithStock(ctx context.Context, reservations []repository.StockReservation, build func([]model.Product) ([]*model.Order, error)) ([]*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrdersWithStock", ctx, reservations, build)
	ret0, _ := ret[0].([]*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrdersWithStock indicates an expected call of CreateOrdersWithStock.
func (mr *MockOrderRepositoryMockRecorder) CreateOrdersWithStock(ctx, reservations, build any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrdersWithStock", reflect.TypeOf((*MockOrderRepository)(nil).CreateOrdersWithStock), ctx, reservations, build)
}

// FindByID mocks base method.
func (m *MockOrderRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockOrderRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockOrderRepository)(nil).FindByID), ctx, id)
}

// FindByStoreID mocks base method.
func (m *MockOrderRepository) FindByStoreID(ctx context.Context, storeID uuid.UUID, page, perPage int) ([]model.Order, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStoreID", ctx, storeID, page, perPage)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByStoreID indicates an expected call of FindByStoreID.
func (mr *MockOrderRepositoryMockRecorder) FindByStoreID(ctx, storeID, page, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStoreID", reflect.TypeOf((*MockOrderRepository)(nil).FindByStoreID), ctx, storeID, page, perPage)
}

// FindByUserID mocks base method.
func (m *MockOrderRepository) FindByUserID(ctx context.Context, userID uuid.UUID, page, perPage int) ([]model.Order, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID, page, perPage)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockOrderRepositoryMockRecorder) FindByUserID(ctx, userID, page, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockOrderRepository)(nil).FindByUserID), ctx, userID, page, perPage)
}

// FindStalePending mocks base method.
func (m *MockOrderRepository) FindStalePending(ctx context.Context, createdBefore time.Time, limit int) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStalePending", ctx, createdBefore, limit)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStalePending indicates an expected call of FindStalePending.
func (mr *MockOrderRepositoryMockRecorder) FindStalePending(ctx, createdBefore, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStalePending", reflect.TypeOf((*MockOrderRepository)(nil).FindStalePending), ctx, createdBefore, limit)
}

// MarkPaymentFailed mocks base method.
func (m *MockOrderRepository) MarkPaymentFailed(ctx context.Context, orderID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPaymentFailed", ctx, orderID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkPaymentFailed indicates an expected call of MarkPaymentFailed.
func (mr *MockOrderRepositoryMockRecorder) MarkPaymentFailed(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPaymentFailed", reflect.TypeOf((*MockOrderRepository)(nil).MarkPaymentFailed), ctx, orderID)
}

// MarkPaymentSucceeded mocks base method.
func (m *MockOrderRepository) MarkPaymentSucceeded(ctx context.Context, orderID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPaymentSucceeded", ctx, orderID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkPaymentSucceeded indicates an expected call of MarkPaymentSucceeded.
func (mr *MockOrderRepositoryMockRecorder) MarkPaymentSucceeded(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPaymentSucceeded", reflect.TypeOf((*MockOrderRepository)(nil).MarkPaymentSucceeded), ctx, orderID)
}

// UpdateStatusIfCurrent mocks base method.
func (m *MockOrderRepository) UpdateStatusIfCurrent(ctx context.Context, id uuid.UUID, fromStatus, toStatus string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusIfCurrent", ctx, id, fromStatus, toStatus)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatusIfCurrent indicates an expected call of UpdateStatusIfCurrent.
func (mr *MockOrderRepositoryMockRecorder) UpdateStatusIfCurrent(ctx, id, fromStatus, toStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusIfCurrent", reflect.TypeOf((*MockOrderRepository)(nil).UpdateStatusIfCurrent), ctx, id, fromStatus, toStatus)
}
