// Code generated by MockGen. DO NOT EDIT.
// Source: store-service/internal/repository/cart_repository.go
//
// Generated by this command:
//
//	mockgen -source=store-service/internal/repository/cart_repository.go -destination=store-service/internal/mocks/mock_cart_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/1tsndre/mini-go-project/store-service/internal/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCartRepository is a mock of CartRepository interface.
type MockCartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCartRepositoryMockRecorder
	isgomock struct{}
}

// MockCartRepositoryMockRecorder is the mock recorder for MockCartRepository.
type MockCartRepositoryMockRecorder struct {
	mock *MockCartRepository
}

// NewMockCartRepository creates a new mock instance.
func NewMockCartRepository(ctrl *gomock.Controller) *MockCartRepository {
	mock := &MockCartRepository{ctrl: ctrl}
	mock.recorder = &MockCartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartRepository) EXPECT() *MockCartRepositoryMockRecorder {
	return m.recorder
}

// DeleteCart mocks base method.
func (m *MockCartRepository) DeleteCart(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCart", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCart indicates an expected call of DeleteCart.
func (mr *MockCartRepositoryMockRecorder) DeleteCart(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCart", reflect.TypeOf((*MockCartRepository)(nil).DeleteCart), ctx, userID)
}

// GetCart mocks base method.
func (m *MockCartRepository) GetCart(ctx context.Context, userID uuid.UUID) (*model.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCart", ctx, userID)
	ret0, _ := ret[0].(*model.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCart indicates an expected call of GetCart.
func (mr *MockCartRepositoryMockRecorder) GetCart(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockCartRepository)(nil).GetCart), ctx, userID)
}

// SaveCart mocks base method.
func (m *MockCartRepository) SaveCart(ctx context.Context, cart *model.Cart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCart", ctx, cart)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCart indicates an expected call of SaveCart.
func (mr *MockCartRepositoryMockRecorder) SaveCart(ctx, cart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCart", reflect.TypeOf((*MockCartRepository)(nil).SaveCart), ctx, cart)
}
